//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Food;

    public partial class CartDetail
    {
        FoodStoreEntities db = new FoodStoreEntities();
        public int CartDetailID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public int ShoppingCartID { get; set; }
        public Nullable<bool> PayNeed { get; set; }

        public virtual Product Product { get; set; }
        public virtual ShoppingCard ShoppingCard { get; set; }
        public Double TotalPrice
        {
            get { return Convert.ToDouble(Quantity * Price); }
        }
        public CartDetail(int msp)
        {
            ProductID = msp;
            Product sp = db.Products.Single(n => n.ProductID == ProductID);
            Quantity = 1;
            Price = sp.Price;
        }
        public CartDetail()
        {

        }
    }
}
