//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect
    {
        public int ID_collect { get; set; }
        public int AccountID { get; set; }
        public int PromotionID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
